SELECT
  O.CUSTOMER_ID        AS customerId,
  O.PID                AS orderId,
  O.EFFECTIVESTARTDATE AS startDate,
  O.EFFECTIVEENDDATE   AS endDate,
  CS.ID                AS chargeSchemaId,
  CSA.ATTRIBUTE_NAME   AS attrName,
  CSA.ATTRIBUTE_VALUE  AS attrValue
FROM
  B_ORDER O,
  B_CHARGE_SCHEME CS,
  B_CHARGE_SCHEME_ATTRIBUTES CSA
WHERE
  O.CUSTOMER_ID = :customerId
  AND O.EFFECTIVEENDDATE > :startDate
  AND O.EFFECTIVESTARTDATE < :endDate
  AND O.CHARGE_ID = CS.ID
  AND O.STATE IN ('IN_EFFECT', 'END_OF_LIFE')
  AND CS.TYPE = 'PSTN_STANDARD_CHARGE'
  AND CSA.SCHEME_ID = CS.ID
  AND CSA.ATTRIBUTE_NAME IN (
    'COMMON_SITES',
    'PSTN_RATES_ID'
  )