SELECT
  O.CUSTOMER_ID        customerId,
  O.PID                orderId,
  O.EFFECTIVEENDDATE   endDate,
  O.EFFECTIVESTARTDATE startDate,
  CS.ID                chargeSchemaId,
  CS.TYPE              packageType,
  CSA.ATTRIBUTE_NAME   attrName,
  CSA.ATTRIBUTE_VALUE  attrValue
FROM
  B_ORDER O,
  B_CHARGE_SCHEME CS,
  B_CHARGE_SCHEME_ATTRIBUTES CSA
WHERE
  O.EFFECTIVEENDDATE > :startDate
  AND O.EFFECTIVESTARTDATE < :endDate
  AND O.CHARGE_ID = CS.ID
  AND CS.ID = CSA.SCHEME_ID
  AND O.STATE IN ('IN_EFFECT', 'END_OF_LIFE')
  AND CS.TYPE IN (
    'PSTN_SINGLE_PACKET_FOR_MULTIPLE_SITES',
    'PSTN_MONTHLY_PACKET',
    'PSTN_SINGLE_PACKET_FOR_ALL_SITES'
  )
  AND CSA.ATTRIBUTE_NAME IN (
    'COMMON_SITES',
    'PSTN_PACKAGE_MINUTES',
    'MONTH_AMOUNT'
  )
  AND O.CUSTOMER_ID = :customerId