SELECT
  DISTINCT O.CUSTOMER_ID customerId
FROM
  B_ORDER O,
  B_CONTRACT C
WHERE
  O.CONTRACT_ID = C.PID
  AND O.STATE IN ('IN_EFFECT', 'END_OF_LIFE')
  AND O.EFFECTIVEENDDATE > :startDate
  AND O.EFFECTIVESTARTDATE < :endDate
  AND C.AGENT_ID = :agentId