SELECT
  O.CUSTOMER_ID,
  O.PID,
  CU.DISPLAY_NAME
FROM
  B_ORDER O,
  B_CONTRACT C,
  B_CUSTOMER CU
WHERE
  O.CONTRACT_ID = C.PID
  AND O.CUSTOMER_ID = CU.PID
  AND O.STATE IN ('IN_EFFECT', 'END_OF_LIFE')
  AND O.EFFECTIVEENDDATE > :startDate
  AND O.EFFECTIVESTARTDATE < :endDate
  AND C.AGENT_ID = :agentId
ORDER BY O.CUSTOMER_ID