SELECT
  DISTINCT O.CUSTOMER_ID AS customerId
FROM
  B_ORDER O, B_CONTRACT C
  LEFT JOIN B_CUSTOMER CUST ON CUST.PID = C.AGENT_ID
WHERE
  O.CONTRACT_ID = C.PID
  AND (C.AGENT_ID IS NULL OR CUST.AGENT_TYPE = 'AGENT')
  AND O.EFFECTIVEENDDATE > :startDate
  AND O.EFFECTIVESTARTDATE < :endDate
  AND O.STATE IN ('IN_EFFECT', 'END_OF_LIFE')